FROM node:23-alpine3.20

# Set environment variables for GitHub Package access
ARG NPM_TOKEN
ENV NPM_TOKEN=${NPM_TOKEN}


WORKDIR /app
COPY package.json ./
COPY tsconfig.json ./
COPY .npmrc ./
COPY src ./src
COPY tools ./tools

RUN npm install
RUN npm install -g nodemon

EXPOSE 4007

CMD ["npm", "run", "dev"]
